### ISSUE TITLE
Expansion pack n64 (read something here)

### ISSUE THREAD

**Issue by eliander30** [fgsfdsfgs/perfect_dark#102]
What is causing lot of non visible textures may be the resolution!

Required for the single player, co-operative and counter-operative campaigns, as well as most multiplayer features. Enables hi-res mode, which increases resolution to 640×222(note here, beyond that i guess there will have errors).

**Comment by fgsfdsfgs** [comment]
No, it's not that. The port already runs in expansion pak mode by default, as you can see in the startup screen. You can turn on the hi-res mode in the options, it won't fix those issues. Probably won't do much of anything, actually.
Most of the texture issues are there because the renderer isn't accurate enough to how the N64 works. This will be fixed over time.
