### ISSUE TITLE
ok but did you fix the skybox yet?

### ISSUE THREAD

**Issue by TuskFGT** [fgsfdsfgs/perfect_dark#122]

**Comment by LanHikariDS** [comment]
OK but did you need to make a second issue for the same problem while being a snarky dickhead about it?
These people are doing this in their own free time for free, and making immense progress in only a month. Posts like this only hurt morale, and I've seen plenty of projects just dropped because of people who contribute nothing being assholes like this. Please remember the person on the other side.

**Comment by rafccq** [comment]
@TuskFGT not sure what your intentions are but indeed your language usage suggests its snarky and entitled as LanHirakiDS mentioned. Plus, like it was said, there is already an open issue for this: #21
When creating issues here, please follow 2 simple rules:
1) Search in the open issues to see if it already exists
2) Provide useful information for the developers: build version used, images/videos if necessary, level etc

The "Issues" page is not for asking if issue X is already solved (the fact there's currently an open issue about it is the answer)

**Comment by fgsfdsfgs** [comment]
No.
