### ISSUE TITLE
Better default controls

### ISSUE THREAD

**Issue by Gorilli09** [fgsfdsfgs/perfect_dark#175]
Action | Nintendo 64 Controller | Controller | Keyboard & Mouse
-- | -- | -- | --
Confirm | A Button | A Button | Enter
Back| B Button | B Button | Backspace
Next Weapon | A Button | D-Pad Right | Mouse Wheel Down
Quick Menu | A Button (hold) | A Button | Q
Previous Weapon | A Button + Z Button | D-Pad Left | Mouse Wheel Up
Reload & Activate | B Button | X Button | Spacebar
Toggle Alternate Fire | B Button (hold) | -- | --
Alternate Fire | B Button + Z Button | RB | Middle Mouse Button
Fire | Z Button | RT | Left Mouse Button
Aim Mode | L/R Button | LT | Right Mouse Button
Quick Detonate | -- | Y Button | E
Crouch | -- | B Button/LB | Left Control
Reset Camera | -- | Right Stick Press | End
<br>

**Comment by fgsfdsfgs** [comment]
You can rebind stuff in pd.ini you know.
For things that can't be rebound it is difficult to find a balance that suits everyone. I will at least try to implement #161 as an option.

**Comment by Graslu** [comment]
The controls you listed above wouldn't work right with the port. If you make W/S work as Control Stick Y-Axis you'll look up and down since it defaults on the 1.2 control scheme. Other choices like space for reloading/use or R/F for zoom are definitely not something the majority would consider "better".

As mentioned already you can modify them to your liking. The only thing the port needs to match 1964 GEPD controls now is CTRL for crouching without the need of aiming.

**Comment by cylonicboom** [comment]
> The controls you listed above wouldn't work right with the port. If you make W/S work as Control Stick Y-Axis you'll look up and down since it defaults on the 1.2 control scheme. Other choices like space for reloading/use or R/F for zoom are definitely not something the majority would consider "better".
> 
> As mentioned already you can modify them to your liking. The only thing the port needs to match 1964 GEPD controls now is CTRL for crouching without the need of aiming.

The three crouch buttons (xbla-style cycle, half-crouch, and full-crouch) requirement is captured here: #42

**Comment by fgsfdsfgs** [comment]
Now that a bind menu is in and also more customization is coming, I'd say it's safe to close this.
