### ISSUE TITLE
Missing DLLs in windows builid

### ISSUE THREAD

**Issue by TwitchBronBron** [fgsfdsfgs/perfect_dark#192]
After running the windows build (`make -f Makefile.port`), I had to manually copy these DLLs into the `build/ntsc-final-port` folder. Perhaps the `make` build could copy those in as well? 
- libgcc_s_dw2-1.dll
- libwinpthread-1.dll
- SDL2.dll
- zlib1.dll

I'm happy to submit a PR if someone could give me a little guidance on how you'd prefer it to be implemented (should I do it in the makefile, can I assume absolute paths like `/mingw32/bin/libgcc_s_dw2-1.dll`, etc...).

**Comment by fgsfdsfgs** [comment]
The automatic builds have the DLLs [bundled](https://github.com/fgsfdsfgs/perfect_dark/blob/port/.github/workflows/c-cpp.yml#L36C11-L36C91). I did not add this to the Makefile because if you're building manually, then it's likely that you're gonna be running the game from the MSYS prompt.
If you want to add this to the Makefile, I'd suggest making another target for that, called something like `dist`.

**Comment by ghost** [comment]
Shouldnt then it be linked static?

**Comment by fgsfdsfgs** [comment]
I would rather leave at least SDL as a dynamic library. You can always replace it with a different version if a new one comes out or a particular one doesn't work in your setup.
This doesn't apply as much to the rest of them, so they could be linked statically, but on Windows that requires you to manually link most dependencies, such as `user32`, `kernel32`, etc, and at the moment when I was writing the Makefile I couldn't be arsed to find out the full list of them.
