### ISSUE TITLE
Multiple issues with the CamSpy.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#20]
1. Portal rendering does not work correctly with the CamSpy, as they will be ignored if too close to the sides of the screen.
<img width="955" alt="camspy portals" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/2ab01b92-9dc6-4004-b878-9efdd7fcaef1">

2. The CamSpy's rotation in the inventory is bugged, it will jitter and shake. In testing I saw this not happen with any other item but it may be a global issue.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/029c9e44-aace-494b-9137-6c3655d4b3bd

3. Mouse look does not work with the CamSpy, you are stuck using the arrow keys to look left/right, hover up/down, and WASD to move it.

**Comment by Lebon14** [comment]
> Mouse look does not work with the CamSpy, you are stuck using the arrow keys to look left/right, hover up/down, and WASD to move it.

Since the controls are not reference anywhere on the page, you don't know how long it took me to figure it out...

For those looking at this, the controls are:
WASD: C-buttons (Selection in menus)
Q: A Button
E: B Button
Left click: Z Button (Accept in menus)
Right click: R Button (Back in menus)
Mouse move: Control stick (ie. look around)
Arrow keys: Control stick
Enter/Return: Start Button
Escape/ESC: unfocus mouse from game

Hopefully controls custumization comes soon.

**Comment by fgsfdsfgs** [comment]
EyeSpy and the Slayer rockets should now support mouse control. The other issues still not fixed.

**Comment by ghost** [comment]
I've also had a crash when placing the Camspy. I'm unsure of the credentials to reproduce it at this very moment, but I feel it's related to the portal rendering issue (unloaded rooms when being placed?)

**Comment by ghost** [comment]
None of these issues occur on the most recent builds, so I'm closing this issue.
