### ISSUE TITLE
radial menu oddities in splitscreen multiplayer

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#204]
Summary of issue:

Player 2's Left Stick doesn't "hold" the radial position in the slot immediately to the left of the center. When the player holds their stick to the left, the radial cursor will hold for a short time before moving back to the center. The c-buttons behave correctly. Also, if the player moves the radial cursor from the both entries immediately diagonally adjacent to (Unarmed, plus the one immediately under it) and back to the leftmost, the cursor will hold correctly with the joystick input.

- 2 players, but only the 2nd player repro was observed.
- platform/build: steam deck / proton / windows

controller / player info:

- player 1: XBox one S Wireless controller
- player 2: Nintendo Switch pro controller
- player 3: unused (builtin steam deck controller?)

**Comment by fgsfdsfgs** [comment]
Does that happen only with that particular controller? Does this happen with Player 3 or 4?
You can set which player the first controller belongs to by changing `FirstGamepadNum` in the ini.
EDIT: Upon further inspection it seems that this only happens if you pull the stick all the way, at least on my knockoff XBOne controller. If you pull it halfway, the selection stays. Overflow somewhere?

**Comment by fgsfdsfgs** [comment]
It was indeed an overflow issue in `activemenutick.c`. With some controllers it is possible to achieve `stick_x = -128`, which then causes issues when it's negated and stored in another `s8`.
