### ISSUE TITLE
Question: Just a few questions.

### ISSUE THREAD

**Issue by MHSlim** [fgsfdsfgs/perfect_dark#281]
Hello, new to using github's issues section but I've been occasionally checking in on the progress of this port and I will say I'm impressed with how far it's come. Makes me optimistic for any future adjustments and additions that can be done. I'm simply curious about a few things concerning this port. I hope I'm not stepping on any toes asking these.

1. Why N64 instead of the remaster/XBLA version? Is there a wall in doing that instead of this? I have no gripes as I mostly prefer N64 anyway but I'm just wondering what made the decision.

2. Would online functionality be a possibility? Given time I'm sure but I imagine it will take a long time to be feasible for both Co-op and Deathmatch. I'm sure this has been asked before but in a sense it's related to question 1 considering I recall XBLA having its own online multiplayer.

3. Mod/texture pack support? I know there aren't that many mods for PD compared to other N64 titles but it'd be nice to know stuff could be optional to use on this port. Texture packs would be nice too since 1964 has the HQ text and such, and the XBLA version has HQ assets and textures as well.

**Comment by fgsfdsfgs** [comment]
1. I didn't rewrite the game from scratch, this is based on the Perfect Dark N64 [decompilation project](https://github.com/n64decomp/perfect_dark). There is no source code or  a similar decomp project for the XBLA version, so this kind of port is not possible for it.
2. Theoretically yes, and in part that's why I started working on the port. But adding it is **a lot** of work, maybe I'll do it eventually, maybe someone else will beat me to it.
3. There is [partial mod support](https://github.com/fgsfdsfgs/perfect_dark/wiki/Modding) already, more or less enough to replace assets and levels. HD texture support is planned.

**Comment by MHSlim** [comment]
> 1. I didn't rewrite the game from scratch, this is based on the Perfect Dark N64 [decompilation project](https://github.com/n64decomp/perfect_dark). There is no source code or  a similar decomp project for the XBLA version, so this kind of port is not possible for it.
> 2. Theoretically yes, and in part that's why I started working on the port. But adding it is **a lot** of work, maybe I'll do it eventually, maybe someone else will beat me to it.
> 3. There is [partial mod support](https://github.com/fgsfdsfgs/perfect_dark/wiki/Modding) already, more or less enough to replace assets and levels. HD texture support is planned.

I see, thank you for the swift response! I was just curious about what was possible or planned and what wasn't. Thank you very much, will continue to use and report anything if I find it. Or brainstorm any additions I think are within the scope of this project.
