### ISSUE TITLE
Area 51: Infiltration Audio Issue With Ending Cutscene

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#286]
This appears to be PC Port exclusive. So when Jonathan says "if what?" he will stutter and say "if if what?" instead of what he's supposed to say in the Outro Cutscene after he shoots the guard in the back. This problem appears in Solo and Co-Op on all difficulties.

**Comment by PeeMoldy** [comment]
> This happens on 1964 GEPD too, possibly a 60FPS(+) issue? Not present on XBLA.

Might be! It doesn't seem to happen on reg n64 cart or ED 64 X7.

**Comment by RyanDwyer** [comment]
This is happening due to a bug in the AI list. It's reusing label 0x6c. Labels that are used for loops should be unique within each AI list.

	wait_until(406, 0x6c) // first usage of 0x6c
	speak(CHR_P1P2, L_LUE_069, MP3_0423, CHANNEL_5, COLOR_07_RED) // "If what?"

	wait_until(410, 0x6a)
	play_sound(SFX_0176, CHANNEL_6)

	wait_until(424, 0x6b)
	play_sound(SFX_0177, CHANNEL_6)

	wait_until(426, 0x6c) // second usage of 0x6c
	play_sound(SFX_0177, CHANNEL_7)

The `wait_until` macro is:

	#define wait_until(time, loopid) \
		beginloop(loopid) \
			if_controller_button_pressed(/*goto*/ 0x54) \
			if_timer_gt(time, /*goto*/ 0x06) \
		endloop(loopid) \
		label(0x06)

`beginloop` defines the label and yields for a frame, and the `endloop` macro expands to `goto_first(label)`.

On N64, it's impossible for it to hit the `endloop` (`goto_first`) on the last `wait_until` wait due to the bigger tick delta. On the port it gets hit and jumps back to the first 0x6c, causing it to execute the "If what" a second time. The condition doesn't trigger again after that because the cutscene timer is already past 426.

A proper fix would be to correct the AI list, but since the port is loading it as a binary asset that becomes difficult. A somewhat clean fix would be to find/replace the byte sequence when loading the setup file. An uglier fix would be to change the aiSpeak function to check if that sound number has already been played and avoid playing it a second time.

**Comment by PeeMoldy** [comment]
> This is happening due to a bug in the AI list. It's reusing label 0x6c. Labels that are used for loops should be unique within each AI list.
> 
> ```
> wait_until(406, 0x6c) // first usage of 0x6c
> speak(CHR_P1P2, L_LUE_069, MP3_0423, CHANNEL_5, COLOR_07_RED) // "If what?"
> 
> wait_until(410, 0x6a)
> play_sound(SFX_0176, CHANNEL_6)
> 
> wait_until(424, 0x6b)
> play_sound(SFX_0177, CHANNEL_6)
> 
> wait_until(426, 0x6c) // second usage of 0x6c
> play_sound(SFX_0177, CHANNEL_7)
> ```
> 
> The `wait_until` macro is:
> 
> ```
> #define wait_until(time, loopid) \
> 	beginloop(loopid) \
> 		if_controller_button_pressed(/*goto*/ 0x54) \
> 		if_timer_gt(time, /*goto*/ 0x06) \
> 	endloop(loopid) \
> 	label(0x06)
> ```
> 
> `beginloop` defines the label and yields for a frame, and the `endloop` macro expands to `goto_first(label)`.
> 
> On N64, it's impossible for it to hit the `endloop` (`goto_first`) on the last `wait_until` wait due to the bigger tick delta. On the port it gets hit and jumps back to the first 0x6c, causing it to execute the "If what" a second time. The condition doesn't trigger again after that because the cutscene timer is already past 426.
> 
> A proper fix would be to correct the AI list, but since the port is loading it as a binary asset that becomes difficult. A somewhat clean fix would be to find/replace the byte sequence when loading the setup file. An uglier fix would be to change the aiSpeak function to check if that sound number has already been played and avoid playing it a second time.

Good work on finding that!

**Comment by fgsfdsfgs** [comment]
This should be fixed now. After the autobuild is finished.
It should also now be easier to add patches for other files.

**Comment by PeeMoldy** [comment]
> This should be fixed now. After the autobuild is finished. It should also now be easier to add patches for other files.

Yep it's definitely fixed. Good work with the new patcher!

**Comment by PeeMoldy** [comment]
And now this can be closed.
