### ISSUE TITLE
Build 460 is bugged!

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#304]
I test versions when they are 10 by 10. This build is a downgrade compared to the old ones. Already, the first thing when you start a new game, it sets the configuration of the controller to N64 and not for the PC port. The other problem is when you start the DataDyne Central level, there is some sort of strange bug that causes the game to not run at 60 FPS.

**Comment by fgsfdsfgs** [comment]
Build 460 is for pull request #300. To download the latest builds for the mainline `port` branch, either use the link in the README or make sure you pay attention to this part here, it should say "Commit X" instead of "Pull request #X":
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/7edeff4f-d517-406f-873f-04a0e5623ee9)
If you are reporting an issue with that particular PR, please post it in the comments for that PR.

**Comment by Bobbar** [comment]
Woopsie!  I just saw that I nuked the .extcontrols default value set.

Fixed in: 880a7a0971b07afbceb02c6cc4039e9716d963e4
