### ISSUE TITLE
Please make an 'easy' version for PAL

### ISSUE THREAD

**Issue by JustJeff88** [fgsfdsfgs/perfect_dark#345]
I am posting to ask you to put up an 'easy' version for the PAL version of PD, as you did for the ntsc version. The PAL version is EFIGS (English, French, Italian, German, Spanish) and would open the project up to people who speak languages other than English. I know that you left instructions for using the PAL rom, but that is beyond the tech skills of most people. I would also point out that the instructions that you gave are only in English also, which means that non-anglophones wouldn't be able to use them regardless.

**Comment by fgsfdsfgs** [comment]
This has been asked many times, so no need to create new issues about it. The reason it is like this right now is twofold:
1. At earlier stages of development it was much easier to test and fix things when everyone was using the same version. Maintaining several different builds would've been too much work. Now it's a bit better though.
2. The current implementation of support for other ROMs is more of a workaround than a proper solution, and as such the PAL builds still have the 50 FPS cap, for example. I'd rather like to support multiple languages and ROM versions with one executable, but that requires some additional work.

I will set up autobuilds for PAL and JPN at some point in the near future since there are evidently people interested in them. I'll reply in this issue and other related ones when that is done.

**Comment by JustJeff88** [comment]
I hope that I did not cause any offence. I'm very grateful for this project and I actually do not have strong feelings one way or the other on the 50/60 issue, but my preferred language is French and I have Francophone and Italian friends who would like to play this in their mother tongues. If you can ever get to the point where there is one 'universal' package with all of the language options and a 50/60 switch, that would be great. 

I simply feel that it makes more sense, if one has to focus on one version, to choose first the line that is in English AND French AND Italian etc rather than just the English one. The custom N64 emulator for this game did the same thing and only supported the NTSC version, which is monolingual. Again, thank you for making this classic game accessible again. The widescreen support is a very nice touch.

**Comment by fgsfdsfgs** [comment]
Don't worry, you did not. I'm a bit busy right now with other things, but at some point I'll get back to the autobuild system.

**Comment by fgsfdsfgs** [comment]
Automatic builds now include executables for PAL and JPN.
