### ISSUE TITLE
Menu "Snake" should render on top of everything else

### ISSUE THREAD

**Issue by tunbridgep** [fgsfdsfgs/perfect_dark#364]
This isn't really a bug per se, as it was present in the original, however I believe the "snake" thing that appears when you open the menus should be drawn on top of everything else, similar to how the players gun is.

Otherwise, it clips through walls. See example:

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/31608726/446196a0-2894-4301-a99d-7be93bef664f)
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/31608726/419ca2ea-6dfe-488f-bfba-655ac1965da9)

Depending on how simple this ends up being to implement, I would be willing to have a go at it, as I have been meaning to potentially contribute and it may be a good way to get my feet wet with the codebase.

(NOTE: This was done with the realtime menus fork at https://github.com/fgsfdsfgs/perfect_dark/pull/358. This issue is more noticeable there because there's no black screen, but you can still see the snake go through walls in the regular version, before and after the screen goes to black to show the menu.)

**Comment by fgsfdsfgs** [comment]
Yeah, this actually is worse in the port than on N64. It also affects weapon models: see #18. This is because depth range shifting for view model rendering is implemented differently (and probably very incorrectly) in the port compared to N64. If you want to take a look, `G_MW_PERSPNORM`/`gSPPerspNormalize` are the things to look for, I think.
Since #18 includes this problem, I'll close this issue. Feel free to post any comments in that one.
