### ISSUE TITLE
Portable Installation (Don't put .ini settings in .local directory on steam deck)

### ISSUE THREAD

**Issue by jacfalcon0** [fgsfdsfgs/perfect_dark#385]
Is it possible to have the pd.ini file generated in the same folder as everything else rather than elsewhere? Very annoying to navigate to hidden system folders on Steam Deck and have to manually change the settings on any of my installs.

**Comment by fgsfdsfgs** [comment]
Yes. If `pd.exe` is in a writable directory, either create an empty `pd.ini` in it or copy the saves and config from the original save directory into it.

**Comment by jacfalcon0** [comment]
So if I copy the pd.ini file from home/.local/share/perfectdark to my pd.exe it will find it there and use it?

Why not have it generated there in the first place?

I haven't run the game yet, but are you saying the saves will go to that system folder too? I guess I'm just not sure what the advantage is of doing things this way when it could all be in the install folder.

**Comment by fgsfdsfgs** [comment]
On Linux binaries are commonly stored in non-writable directories such as `/usr/bin`, so the game assumes that this will be the case and creates the saves and configs in `~/.local/share/perfectdark` by default. If it detects a config file (`pd.ini`) next to the binary, it will use the binary folder instead, for both saves and configs.

**Comment by jacfalcon0** [comment]
So once I put my pd.ini in the same folder it will also generate saves in that folder?

Seems like it would be more helpful to attempt by default to put it in the same folder, and then if that doesn't work put it in the .local directory?

**Comment by fgsfdsfgs** [comment]
Yes. You can also just create an empty `pd.ini` and it will also work.

The latter is more or less how it works on Windows, but I made it default to `~/` on Linux since that's way more common over there, in my experience, and also at the time it was requested for [flatpak support](https://github.com/fgsfdsfgs/perfect_dark/pull/165). Really up to preference what the default is.

UPD: Oh yeah, I forgot. You can also just specify the  `--portable` command line parameter.

**Comment by jacfalcon0** [comment]
Awesome, thanks for the help!
