### ISSUE TITLE
3DS port

### ISSUE THREAD

**Issue by catskull** [fgsfdsfgs/perfect_dark#386]
A 3DS port seems possible - 32 bit, OpenGL, etc. Unsure about SDL2. 

Here is a diff of the 3DS port of the Mario 64 decomp: https://github.com/sm64-port/sm64-port/compare/master...mkst:sm64-port:3ds-port

**Comment by fgsfdsfgs** [comment]
I don't have a 3DS and haven't really written any 3DS homebrew. If someone wants to do one, they can try, but I probably won't. I'm willing to wager the renderer will have to be rewritten since the current one requires at the very least GL2.1 and GLSL, and it could probably only run on an N3DS, if at all.
