### ISSUE TITLE
Support for GameShark codes

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#397]
Hey, I don't know if this version supports GameShark codes, but I think it would be a cool feature to have because I created a bunch of custom weapons using GameShark codes and would love to be able to use them in this version.

**Comment by fgsfdsfgs** [comment]
Not quite possible because GameShark codes are essentially memory editing and we can't really do that in a native PC port for many reasons. It is theoretically possible to "simulate" the effects of known codes, but it would be much better to just expand existing cheats and modding capabilities.

Editing at least some weapon attributes is probably going to be available in some shape or form on the PC port as a modding feature though.
