### ISSUE TITLE
Make it easier to just download Region-Exe

### ISSUE THREAD

**Issue by Manaplayer** [fgsfdsfgs/perfect_dark#414]
Hello. It's definitely great that this program exists. My problem, and I'm sure there will be some who have never had anything to do with programming, is meeting these requirements for a PAL version. I tried it on Windows and Linux but nothing happens other than error messages. I have installed all the stuff that is specified. Can't you just provide the pd.exe as US-PAL-JPN, fully compiled?

**Comment by fgsfdsfgs** [comment]
Yeah, this has been requested before. I'll add autobuilds for other regions at some point.  
Eventually I want a single binary solution for all regions, but for now that will have to do.

**Comment by ThisNekoGuy** [comment]
@fgsfdsfgs 
I wrote an `sh` script for non-Windows systems that interactively (includes options for region type) builds the executable and installs it in a local path (without `sudo`) and writes a desktop entry for launching the game for desktop application launchers.
(Doesn't write the desktop entry for MacOS because I've never owned a Mac and don't know how MacOS handles desktop entries.)

If you want, I can create a PR for it so that this is a solution in the meantime (or for anyone who just wants/needs to build against the latest commit).

**Comment by fgsfdsfgs** [comment]
I already added region-specific EXEs to automatic builds yesterday.

**Comment by fgsfdsfgs** [comment]
Since there are autobuilds for all regions now I'll close this. This will become better when the single-executable thing is implemented.
