### ISSUE TITLE
Blue line on Carrington Villa level

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#505]
![564564654](https://github.com/user-attachments/assets/9f65f761-7906-46e6-8721-b907759abf48)

I don't know if it was in old builds, but I just noticed that there was this graphical bug.

**Comment by fgsfdsfgs** [comment]
It has always been there. These are seams in map geometry as far as I can tell and they're unfortunately not really fixable. What is fixable though is the sun shining through them, but I'd argue that's a different issue.

**Comment by megatog615** [comment]
I believe there is a possible way to fix this. Other engines such as Quake 3 actually do a little bit of "re-stitching" at either map compile or in loading. I think it works by running through the map geometry and finding vertices that are extremely close together and snapping them to a grid, of sorts(sorta like quantization). This may have been useless on the N64 because it was nearly unnoticeable at the resolution it ran at.

**Comment by fgsfdsfgs** [comment]
This is something to experiment with, as there probably are places where this might result in decals merging into the surface they're on. I know Quake-based engines have an option to remove T-junctions as well, but that's a bit of a different issue.

**Comment by megatog615** [comment]
I have a feeling that there aren't enough misaligned vertices in the game's levels to worry about decals, but surely pd has a way of differentiating surfaces as "level geometry" and "detail" or "decal" or something that you can skip those surfaces?
