### ISSUE TITLE
Startup crash on GLES devices

### ISSUE THREAD

**Issue by ben-willmore** [fgsfdsfgs/perfect_dark#556]
Hello, I've been trying the 64 bit builds out on Anbernic (etc) aarch64 devices which use GLES. It seems to work really well, much better than an N64 emulator. However, one line causes problems:

port/fast3d/gfx_sdl2.cpp:
```
SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
```
On some devices with GLES only, this fails because SDL_GL_CONTEXT_PROFILE_COMPATIBILITY is not available (only SDL_GL_CONTEXT_PROFILE_ES). On others with older OS, it fails with `Can't window GBM/EGL surfaces on window creation.` because they don't allow GL profile to be set until after window creation.

My understanding is that this line only sets the GL profile of the window temporarily for the window creation process, and the real setup happens later. This suggests to me that the line is not necessary. The game runs fine on these devices and others if it is simply commented out.

**Comment by fgsfdsfgs** [comment]
If it errors out (i.e. `SDL_CreateWindow` returns `NULL` and the game exits with a fatal error message), then this should probably be rewritten to retry creating the window the same way it does with the context below. I assumed you're supposed to set the attributes before creating the context, but it seems like you actually have to do it even before creating the window itself.

If it actually *crashes* with no error message, then this would probably be a bug in SDL2 similar to [this](https://github.com/libsdl-org/SDL/issues/11482), since the window/context creation is supposed to fail gracefully if the requested version is not available.

**Comment by ben-willmore** [comment]
These are both errors as opposed to crashes. Trying again with SDL_GL_CONTEXT_PROFILE_ES works fine in the first case (where the device just doesn't support SDL_GL_CONTEXT_PROFILE_COMPATIBILITY). I'm not sure if it will work in the second case (`Can't window GBM/EGL surfaces on window creation.`). I don't have access to the device where the second case happens, so it's hard to know, especially given the seemingly garbled error message.

**Comment by fgsfdsfgs** [comment]
This should be fixed with [a14e9ed](https://github.com/fgsfdsfgs/perfect_dark/commit/a14e9ed97ef3e02b48bbd899f0e17c6161831b54). It will retry creating the window when it iterates through GL context versions.

If you need it to immediately create a ES context, you can pass e.g. `--gl-version 3.0es` on the command line.

**Comment by fgsfdsfgs** [comment]
I'll close this then. Comment if it's still broken.

**Comment by ben-willmore** [comment]
fixed, thank you!
