### ISSUE TITLE
[Feature Request] Fix geomtery seams around portals.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#62]
![seams](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/b1c076ab-5412-48f2-8125-ee909ec5dc6c)

![seams2](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/c00b24ed-9312-4c98-8e79-23a3333fb2b5)

There is noticeable seams around portals that will shift and create holes in the geometry depending on your view. This happens occasionally in GoldenEye when there's mismatches between room and portal geometry, but in Perfect Dark these seams are nearly everywhere.

I'm assuming this is caused by some sort of rounding/precision error with portal coords under https://github.com/fgsfdsfgs/perfect_dark/blob/8c9c0abee637fd0bb18dfec91fc6a007b3903a88/src/game/portalconv_c.c

**Comment by RyanDwyer** [comment]
Portals only determine which rooms to display, not how to clip them. I suspect the issue is that the actual geometry doesn't align, and wasn't noticeable on the N64 due to its low resolution.

Edit: Actually, I've changed my mind. in your first screenshot you can see the corner in the mid left of the image has issues. Even if the geometry was wrong, there wouldn't be a blue line there. So it must be something else.

**Comment by fgsfdsfgs** [comment]
It could also be caused by rounding issues in the scissor coord scaling function in gfx_pc.cpp. I'll need to check that out.
I've also noticed it's almost as if portals update slightly slower than you move, so the seams kind of "trail behind" the camera.
Edit: Kind of looks like the bounding boxes for the portals are too tight, so if you look at them at a slight angle, seams are more evident.

**Comment by ghost** [comment]
I also feel it also could be related to the low-precision snapping effect on the stars in the Defection skybox, and on screen sight, as it also has that "trail behind" look to it, but that's a guess at most.

**Comment by tmyqlfpir** [comment]
I believe the issue is caused by `bgScissorWithinViewport()` - perhaps it could be adjusted to overdraw by a single pixel.

**Comment by fgsfdsfgs** [comment]
I extended the scissor margins slightly, maybe this is enough to fix it?

**Comment by ghost** [comment]
The seams between portals have now disappeared. On the second screenshot you can see seams with the window, but it was likely a manually placed prop and thus has a far larger gap than portals, so it isn't an issue.
![after1](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/dc86fd14-48d8-4a59-9755-95fc8470fc25)
![after2](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/be907a91-0636-4def-bc8f-38731ea116b1)

**Comment by fgsfdsfgs** [comment]
There are still plenty of seams in the geometry itself. I suspect that this is what that is. Don't think we can easily fix those. Will leave this open for a bit in case this broke something.

**Comment by fgsfdsfgs** [comment]
Guess it didn't.
