### ISSUE TITLE
Steam Deck support?

### ISSUE THREAD

**Issue by BlackRNG** [fgsfdsfgs/perfect_dark#83]
Anything steam deck related in plan? Would love to have dual stick, gyro and touch support.

**Comment by fgsfdsfgs** [comment]
You should already be able to play it with two sticks and build it for the Steam Deck. The rest will possibly be added in the future, but honestly that's pretty low priority.

**Comment by Graslu** [comment]
It already works, and you can configure gyro to work as mouse for precise aiming.

**Comment by megatog615** [comment]
Perhaps a flatpak could be made for easy install?

**Comment by BlackRNG** [comment]
Just tried with the gyro assigned to the joystick (mouse didn't work) and looks like there's some kind of low pass filter going on.
[final.webm](https://github.com/fgsfdsfgs/perfect_dark/assets/48617661/6666524c-41a8-4b72-959e-9686ca39c870)

**Comment by Graslu** [comment]
Map all the controls to keyboard and mouse so there's no conflicts, and map gyro to turn on when you hold the left trigger. The crosshair isn't dynamic like in 1964 GEPD but it works for now.

**Comment by Ronald-Diemicke** [comment]
So running the Linux version on the steam deck seems to need SDL 2 as a dependency… but considering how the OS is locked down, you can’t really install it. 

The pc version seems to work with specific versions of proton but sound doesn’t seem to work

**Comment by BlackRNG** [comment]
> Perhaps a flatpak could be made for easy install?

It was very easy to compile


> So running the Linux version on the steam deck seems to need SDL 2 as a dependency… but considering how the OS is locked down, you can’t really install it.

Having the SDL2 .so file and using LD_LIBRARY_PATH should do the trick.

**Comment by megatog615** [comment]
> Having the SDL2 .so file and using LD_LIBRARY_PATH should do the trick.

You can also add it to the Steam app on the deck as a non-Steam game and force it to use the Steam Linux Runtime.

> It was very easy to compile

True but the primary way to install software on the Deck outside of the Steam client is through flatpaks. It would make it available for for people less inclined to compile it or manually unpack the build and set up an install.

**Comment by Ronald-Diemicke** [comment]
Yup - I got this working with the comments above. Used Lutris to add it to steam using the linux runtime. Thanks!

**Comment by cpelley** [comment]
Got working fine after setting Steam Linux Runtime in compatibility as well as ensuring ROM name precisely as it expects, ergo 'pd.ntsc-final.z64'. Getting the game to take up the whole screen by setting the full screen option under the ini file.

**Comment by The-MAZZTer** [comment]
I got it working on Deck with @cpelley's instructions. Here is an expanded step list I put together:

1. Drop Linux build + ROM on Deck somewhere.
2. Open Steam desktop client.
3. Add non-Steam game, browse for game.
4. Select "all files" from the dropdown so you can select pd.
5. Add game to Steam.
6. Right click (long press) pd and hit properties.
7. Rename pd to Perfect Dark (needed if you want a steam grid db tool to find anything).
8. Go to compatibility tab and enable compatibility, and select "Steam Linux Runtime 1.0 (scout)" from the dropdown.
9. Run game through Steam desktop client to make sure game starts up (and generate pd.ini file). Close game.
10. Open up ~/.local/share/perfectdark/pd.ini in a text editor.
11. Adjust anything you want here. See below for my recommended video settings.
12. Switch to gaming mode and make sure game runs here properly (game is full screen and proper aspect ratio etc).
13. Find grid art using BoilR or the Decky SteamGridDB plugin or whatever. Restart Steam as needed to apply changes.

Video settings (I didn't adjust MSAA or texture filtering, you can experiment with those if you want.):

    DefaultWidth=1280
    DefaultHeight=800
    DefaultFullscreen=1
    VSync=0

VSync shouldn't be needed since the Deck enforces it on its own.

**Comment by fgsfdsfgs** [comment]
I'll close this since it evidently works just fine on the Deck.

**Comment by cpelley** [comment]
> I'll close this since it evidently works just fine on the Deck.

Completed the game on the deck :)
Thank you so much for your work on this.
Loved this game so much when it came out, amazing to be able to play it properly now properly.
